package com.onlinepay.manage.dao.payment.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CocoAgentRate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.AGENT_NO
     *
     * @mbg.generated
     */
    private String agentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.AGENT_L1_RATE
     *
     * @mbg.generated
     */
    private BigDecimal agentL1Rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.AGENT_L2_RATE
     *
     * @mbg.generated
     */
    private BigDecimal agentL2Rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.USER_FEE_DF19
     *
     * @mbg.generated
     */
    private Double userFeeDf19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.USER_FEE_DF20
     *
     * @mbg.generated
     */
    private Double userFeeDf20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.USER_RATE19
     *
     * @mbg.generated
     */
    private BigDecimal userRate19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.USER_RATE20
     *
     * @mbg.generated
     */
    private BigDecimal userRate20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.AGENT_L1_FEE
     *
     * @mbg.generated
     */
    private Double agentL1Fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.AGENT_L2_FEE
     *
     * @mbg.generated
     */
    private Double agentL2Fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coco_agent_rate.TIME
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public CocoAgentRate(Integer id, String agentNo, BigDecimal agentL1Rate, BigDecimal agentL2Rate, Double userFeeDf19, Double userFeeDf20, BigDecimal userRate19, BigDecimal userRate20, Double agentL1Fee, Double agentL2Fee, Date time) {
        this.id = id;
        this.agentNo = agentNo;
        this.agentL1Rate = agentL1Rate;
        this.agentL2Rate = agentL2Rate;
        this.userFeeDf19 = userFeeDf19;
        this.userFeeDf20 = userFeeDf20;
        this.userRate19 = userRate19;
        this.userRate20 = userRate20;
        this.agentL1Fee = agentL1Fee;
        this.agentL2Fee = agentL2Fee;
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public CocoAgentRate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.ID
     *
     * @return the value of coco_agent_rate.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.ID
     *
     * @param id the value for coco_agent_rate.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.AGENT_NO
     *
     * @return the value of coco_agent_rate.AGENT_NO
     *
     * @mbg.generated
     */
    public String getAgentNo() {
        return agentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.AGENT_NO
     *
     * @param agentNo the value for coco_agent_rate.AGENT_NO
     *
     * @mbg.generated
     */
    public void setAgentNo(String agentNo) {
        this.agentNo = agentNo == null ? null : agentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.AGENT_L1_RATE
     *
     * @return the value of coco_agent_rate.AGENT_L1_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getAgentL1Rate() {
        return agentL1Rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.AGENT_L1_RATE
     *
     * @param agentL1Rate the value for coco_agent_rate.AGENT_L1_RATE
     *
     * @mbg.generated
     */
    public void setAgentL1Rate(BigDecimal agentL1Rate) {
        this.agentL1Rate = agentL1Rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.AGENT_L2_RATE
     *
     * @return the value of coco_agent_rate.AGENT_L2_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getAgentL2Rate() {
        return agentL2Rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.AGENT_L2_RATE
     *
     * @param agentL2Rate the value for coco_agent_rate.AGENT_L2_RATE
     *
     * @mbg.generated
     */
    public void setAgentL2Rate(BigDecimal agentL2Rate) {
        this.agentL2Rate = agentL2Rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.USER_FEE_DF19
     *
     * @return the value of coco_agent_rate.USER_FEE_DF19
     *
     * @mbg.generated
     */
    public Double getUserFeeDf19() {
        return userFeeDf19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.USER_FEE_DF19
     *
     * @param userFeeDf19 the value for coco_agent_rate.USER_FEE_DF19
     *
     * @mbg.generated
     */
    public void setUserFeeDf19(Double userFeeDf19) {
        this.userFeeDf19 = userFeeDf19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.USER_FEE_DF20
     *
     * @return the value of coco_agent_rate.USER_FEE_DF20
     *
     * @mbg.generated
     */
    public Double getUserFeeDf20() {
        return userFeeDf20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.USER_FEE_DF20
     *
     * @param userFeeDf20 the value for coco_agent_rate.USER_FEE_DF20
     *
     * @mbg.generated
     */
    public void setUserFeeDf20(Double userFeeDf20) {
        this.userFeeDf20 = userFeeDf20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.USER_RATE19
     *
     * @return the value of coco_agent_rate.USER_RATE19
     *
     * @mbg.generated
     */
    public BigDecimal getUserRate19() {
        return userRate19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.USER_RATE19
     *
     * @param userRate19 the value for coco_agent_rate.USER_RATE19
     *
     * @mbg.generated
     */
    public void setUserRate19(BigDecimal userRate19) {
        this.userRate19 = userRate19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.USER_RATE20
     *
     * @return the value of coco_agent_rate.USER_RATE20
     *
     * @mbg.generated
     */
    public BigDecimal getUserRate20() {
        return userRate20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.USER_RATE20
     *
     * @param userRate20 the value for coco_agent_rate.USER_RATE20
     *
     * @mbg.generated
     */
    public void setUserRate20(BigDecimal userRate20) {
        this.userRate20 = userRate20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.AGENT_L1_FEE
     *
     * @return the value of coco_agent_rate.AGENT_L1_FEE
     *
     * @mbg.generated
     */
    public Double getAgentL1Fee() {
        return agentL1Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.AGENT_L1_FEE
     *
     * @param agentL1Fee the value for coco_agent_rate.AGENT_L1_FEE
     *
     * @mbg.generated
     */
    public void setAgentL1Fee(Double agentL1Fee) {
        this.agentL1Fee = agentL1Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.AGENT_L2_FEE
     *
     * @return the value of coco_agent_rate.AGENT_L2_FEE
     *
     * @mbg.generated
     */
    public Double getAgentL2Fee() {
        return agentL2Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.AGENT_L2_FEE
     *
     * @param agentL2Fee the value for coco_agent_rate.AGENT_L2_FEE
     *
     * @mbg.generated
     */
    public void setAgentL2Fee(Double agentL2Fee) {
        this.agentL2Fee = agentL2Fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coco_agent_rate.TIME
     *
     * @return the value of coco_agent_rate.TIME
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coco_agent_rate.TIME
     *
     * @param time the value for coco_agent_rate.TIME
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}