package com.onlinepay.manage.dao.payment.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CocoAgentRateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public CocoAgentRateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAgentNoIsNull() {
            addCriterion("AGENT_NO is null");
            return (Criteria) this;
        }

        public Criteria andAgentNoIsNotNull() {
            addCriterion("AGENT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAgentNoEqualTo(String value) {
            addCriterion("AGENT_NO =", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoNotEqualTo(String value) {
            addCriterion("AGENT_NO <>", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoGreaterThan(String value) {
            addCriterion("AGENT_NO >", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoGreaterThanOrEqualTo(String value) {
            addCriterion("AGENT_NO >=", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoLessThan(String value) {
            addCriterion("AGENT_NO <", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoLessThanOrEqualTo(String value) {
            addCriterion("AGENT_NO <=", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoLike(String value) {
            addCriterion("AGENT_NO like", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoNotLike(String value) {
            addCriterion("AGENT_NO not like", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoIn(List<String> values) {
            addCriterion("AGENT_NO in", values, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoNotIn(List<String> values) {
            addCriterion("AGENT_NO not in", values, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoBetween(String value1, String value2) {
            addCriterion("AGENT_NO between", value1, value2, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoNotBetween(String value1, String value2) {
            addCriterion("AGENT_NO not between", value1, value2, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateIsNull() {
            addCriterion("AGENT_L1_RATE is null");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateIsNotNull() {
            addCriterion("AGENT_L1_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateEqualTo(BigDecimal value) {
            addCriterion("AGENT_L1_RATE =", value, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateNotEqualTo(BigDecimal value) {
            addCriterion("AGENT_L1_RATE <>", value, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateGreaterThan(BigDecimal value) {
            addCriterion("AGENT_L1_RATE >", value, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AGENT_L1_RATE >=", value, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateLessThan(BigDecimal value) {
            addCriterion("AGENT_L1_RATE <", value, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AGENT_L1_RATE <=", value, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateIn(List<BigDecimal> values) {
            addCriterion("AGENT_L1_RATE in", values, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateNotIn(List<BigDecimal> values) {
            addCriterion("AGENT_L1_RATE not in", values, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGENT_L1_RATE between", value1, value2, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL1RateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGENT_L1_RATE not between", value1, value2, "agentL1Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateIsNull() {
            addCriterion("AGENT_L2_RATE is null");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateIsNotNull() {
            addCriterion("AGENT_L2_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateEqualTo(BigDecimal value) {
            addCriterion("AGENT_L2_RATE =", value, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateNotEqualTo(BigDecimal value) {
            addCriterion("AGENT_L2_RATE <>", value, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateGreaterThan(BigDecimal value) {
            addCriterion("AGENT_L2_RATE >", value, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AGENT_L2_RATE >=", value, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateLessThan(BigDecimal value) {
            addCriterion("AGENT_L2_RATE <", value, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AGENT_L2_RATE <=", value, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateIn(List<BigDecimal> values) {
            addCriterion("AGENT_L2_RATE in", values, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateNotIn(List<BigDecimal> values) {
            addCriterion("AGENT_L2_RATE not in", values, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGENT_L2_RATE between", value1, value2, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andAgentL2RateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGENT_L2_RATE not between", value1, value2, "agentL2Rate");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19IsNull() {
            addCriterion("USER_FEE_DF19 is null");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19IsNotNull() {
            addCriterion("USER_FEE_DF19 is not null");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19EqualTo(Double value) {
            addCriterion("USER_FEE_DF19 =", value, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19NotEqualTo(Double value) {
            addCriterion("USER_FEE_DF19 <>", value, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19GreaterThan(Double value) {
            addCriterion("USER_FEE_DF19 >", value, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19GreaterThanOrEqualTo(Double value) {
            addCriterion("USER_FEE_DF19 >=", value, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19LessThan(Double value) {
            addCriterion("USER_FEE_DF19 <", value, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19LessThanOrEqualTo(Double value) {
            addCriterion("USER_FEE_DF19 <=", value, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19In(List<Double> values) {
            addCriterion("USER_FEE_DF19 in", values, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19NotIn(List<Double> values) {
            addCriterion("USER_FEE_DF19 not in", values, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19Between(Double value1, Double value2) {
            addCriterion("USER_FEE_DF19 between", value1, value2, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf19NotBetween(Double value1, Double value2) {
            addCriterion("USER_FEE_DF19 not between", value1, value2, "userFeeDf19");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20IsNull() {
            addCriterion("USER_FEE_DF20 is null");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20IsNotNull() {
            addCriterion("USER_FEE_DF20 is not null");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20EqualTo(Double value) {
            addCriterion("USER_FEE_DF20 =", value, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20NotEqualTo(Double value) {
            addCriterion("USER_FEE_DF20 <>", value, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20GreaterThan(Double value) {
            addCriterion("USER_FEE_DF20 >", value, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20GreaterThanOrEqualTo(Double value) {
            addCriterion("USER_FEE_DF20 >=", value, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20LessThan(Double value) {
            addCriterion("USER_FEE_DF20 <", value, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20LessThanOrEqualTo(Double value) {
            addCriterion("USER_FEE_DF20 <=", value, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20In(List<Double> values) {
            addCriterion("USER_FEE_DF20 in", values, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20NotIn(List<Double> values) {
            addCriterion("USER_FEE_DF20 not in", values, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20Between(Double value1, Double value2) {
            addCriterion("USER_FEE_DF20 between", value1, value2, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserFeeDf20NotBetween(Double value1, Double value2) {
            addCriterion("USER_FEE_DF20 not between", value1, value2, "userFeeDf20");
            return (Criteria) this;
        }

        public Criteria andUserRate19IsNull() {
            addCriterion("USER_RATE19 is null");
            return (Criteria) this;
        }

        public Criteria andUserRate19IsNotNull() {
            addCriterion("USER_RATE19 is not null");
            return (Criteria) this;
        }

        public Criteria andUserRate19EqualTo(BigDecimal value) {
            addCriterion("USER_RATE19 =", value, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19NotEqualTo(BigDecimal value) {
            addCriterion("USER_RATE19 <>", value, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19GreaterThan(BigDecimal value) {
            addCriterion("USER_RATE19 >", value, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_RATE19 >=", value, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19LessThan(BigDecimal value) {
            addCriterion("USER_RATE19 <", value, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19LessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_RATE19 <=", value, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19In(List<BigDecimal> values) {
            addCriterion("USER_RATE19 in", values, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19NotIn(List<BigDecimal> values) {
            addCriterion("USER_RATE19 not in", values, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_RATE19 between", value1, value2, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate19NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_RATE19 not between", value1, value2, "userRate19");
            return (Criteria) this;
        }

        public Criteria andUserRate20IsNull() {
            addCriterion("USER_RATE20 is null");
            return (Criteria) this;
        }

        public Criteria andUserRate20IsNotNull() {
            addCriterion("USER_RATE20 is not null");
            return (Criteria) this;
        }

        public Criteria andUserRate20EqualTo(BigDecimal value) {
            addCriterion("USER_RATE20 =", value, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20NotEqualTo(BigDecimal value) {
            addCriterion("USER_RATE20 <>", value, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20GreaterThan(BigDecimal value) {
            addCriterion("USER_RATE20 >", value, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_RATE20 >=", value, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20LessThan(BigDecimal value) {
            addCriterion("USER_RATE20 <", value, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20LessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_RATE20 <=", value, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20In(List<BigDecimal> values) {
            addCriterion("USER_RATE20 in", values, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20NotIn(List<BigDecimal> values) {
            addCriterion("USER_RATE20 not in", values, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_RATE20 between", value1, value2, "userRate20");
            return (Criteria) this;
        }

        public Criteria andUserRate20NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_RATE20 not between", value1, value2, "userRate20");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeIsNull() {
            addCriterion("AGENT_L1_FEE is null");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeIsNotNull() {
            addCriterion("AGENT_L1_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeEqualTo(Double value) {
            addCriterion("AGENT_L1_FEE =", value, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeNotEqualTo(Double value) {
            addCriterion("AGENT_L1_FEE <>", value, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeGreaterThan(Double value) {
            addCriterion("AGENT_L1_FEE >", value, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeGreaterThanOrEqualTo(Double value) {
            addCriterion("AGENT_L1_FEE >=", value, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeLessThan(Double value) {
            addCriterion("AGENT_L1_FEE <", value, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeLessThanOrEqualTo(Double value) {
            addCriterion("AGENT_L1_FEE <=", value, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeIn(List<Double> values) {
            addCriterion("AGENT_L1_FEE in", values, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeNotIn(List<Double> values) {
            addCriterion("AGENT_L1_FEE not in", values, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeBetween(Double value1, Double value2) {
            addCriterion("AGENT_L1_FEE between", value1, value2, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL1FeeNotBetween(Double value1, Double value2) {
            addCriterion("AGENT_L1_FEE not between", value1, value2, "agentL1Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeIsNull() {
            addCriterion("AGENT_L2_FEE is null");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeIsNotNull() {
            addCriterion("AGENT_L2_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeEqualTo(Double value) {
            addCriterion("AGENT_L2_FEE =", value, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeNotEqualTo(Double value) {
            addCriterion("AGENT_L2_FEE <>", value, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeGreaterThan(Double value) {
            addCriterion("AGENT_L2_FEE >", value, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeGreaterThanOrEqualTo(Double value) {
            addCriterion("AGENT_L2_FEE >=", value, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeLessThan(Double value) {
            addCriterion("AGENT_L2_FEE <", value, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeLessThanOrEqualTo(Double value) {
            addCriterion("AGENT_L2_FEE <=", value, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeIn(List<Double> values) {
            addCriterion("AGENT_L2_FEE in", values, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeNotIn(List<Double> values) {
            addCriterion("AGENT_L2_FEE not in", values, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeBetween(Double value1, Double value2) {
            addCriterion("AGENT_L2_FEE between", value1, value2, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andAgentL2FeeNotBetween(Double value1, Double value2) {
            addCriterion("AGENT_L2_FEE not between", value1, value2, "agentL2Fee");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("TIME is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("TIME =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("TIME <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("TIME >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("TIME <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("TIME <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("TIME in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("TIME not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("TIME between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("TIME not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coco_agent_rate
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coco_agent_rate
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}